services:
  image-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/image_downloader
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      GOOGLE_APIKEY: ""
      GOOGLE_CX: ""
      IMAGE_RESIZE_WIDTH: 100
      IMAGE_RESIZE_HEIGHT: 100
    networks:
      - image-downloader

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=image_downloader
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - image-downloader

networks:
  image-downloader:
    name: "image-downloader"
volumes:
  postgres:
    name: "image-downloader-postgres-volume"